<?php 
return array (
  'tp' => '',
  'site_name' => '武汉尚科在线',
  'site_title' => '武汉尚科在线',
  'site_url' => 'http://www.sharkou.com/',
  'logo' => '',
  'erwei' => '',
  'phone' => '4009189918',
  'adress' => '武汉市尚科在线网络技术有限公司',
  'gonggao' => '',
  'gonggaonr' => '',
  'vip0' => '',
  'vip0m' => '',
  'vip1' => '',
  'vip1m' => '',
  'vip2' => '',
  'vip2m' => '',
  'vip3' => '',
  'vip3m' => '',
  'ischeckuser' => 'false',
  'ipc' => '',
  'site_qq' => '',
  'counts' => '',
  'baidu_map_api' => '85302a33ca1579ea39f0c57537a469f4',
  'site_email' => '',
  'about' => '武汉尚科在线网络技术有限公司',
  'keyword' => '武汉尚科在线网络技术有限公司',
  'content' => '武汉尚科在线网络技术有限公司',
  'copyright' => '武汉尚科在线网络技术有限公司',
  'appid'=>'wx5ba4fea25b025a9d',
  'appkey'=>'b4fac72f6df9fab75390deaec779728d',
);